name: Deploy



on:

  push:

    branches: ['main']



jobs:

  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          ref: main
          
      - name: Add remote-url
        run: |
          git remote add forked-repo https://OrangeKim04:${{ secrets.TOKEN }}@github.com/OrangeKim04/frontend
          git config user.name OrangeKim04
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo